### ISSUE TITLE
I think it's better do not auto scroll up when the check box checked or unchecked

### ISSUE THREAD

**Issue by charlie-wong** [mattlag/Unicode-Ninja#13]

**Comment by mattlag** [comment]
Yeah - agree. I think the whole page is re-built with every click. The code would have to be refactored to not redraw the checkboxes, and only redraw the content area.

**Comment by mattlag** [comment]
Fixed in v3.0.0

**Comment by charlie-wong** [comment]
Got it, that looks pretty good, and sorry for response a little bit late!
